import { HeartIcon } from '@heroicons/react/outline';
import Head from 'next/head';
import { useRouter } from 'next/router';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Header from './Header';

export default function Home() {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio | Anmol Reshi</title> 
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main>
          
      <div className="min-w-screen min-h-screen 
      bg-yellow-300 flex items-center p-5 lg:p-10 
      overflow-hidden relative">
    <div className="w-full max-w-6xl rounded bg-white shadow-xl p-10 lg:p-20 mx-auto text-gray-800 relative md:text-left">
        <div className="md:flex items-center -mx-10">
            <div className="w-full md:w-1/2 px-10 mb-10 md:mb-0">
                <div className="relative">
                    <img src="https://i.pinimg.com/originals/2b/e1/2b/2be12bbedf177b644fb6b9525aaa0b3e.png" 
                    className="w-full relative z-10" alt=""/>
                    <div className="border-4 border-yellow-200
                     absolute top-10 bottom-10 left-10 right-10 
                     z-0"></div>
                </div>
            </div>
            <div className="w-full md:w-1/2 px-10">
                <div className="mb-10">
                    <h1 className="font-bold uppercase text-2xl mb-5">Anmol Reshi<br/><span className="text-sm flex">
                       A Web Developer by &nbsp; <HeartIcon className="h-4 fill current text-red-600 "/></span></h1>
                    <p className="text-sm">Hey! I am Anmol Reshi, a Web Developer with 1+ years of experience in the web industry.
                     In past 1 years, I've learnt and gained a lot of experience from Various documentation, videos, online 
                    courses to making pratical implementation at my work.I Love to contribute in Open source and help Student
                     Community Around me and help them to give guided path. am a people's person and I love sharing my experiences
                      to Student Community and learning from Students.
                      I believe one of my favourite quotes describe it very well, "You Learn More From Failure Than From Success.
                       Don’t Let It Stop You. Failure Builds Character.".
                       <br/>
                       I always maintain good relations with my folks, and that is why I
                        can say, My friends, acquaintances and my network are one of 
                        biggest strengths as a person. Right now I am looking for
                         opportunities to move to a completely new place anywhere
                          in the world and begin a new adventure, make more friends 
                          and grow further as a person.. And in case you were wondering,
                        I am more of a Book person, my favourite food are Burger and 
                        Rajma Chawal and I am 6 feet tall.</p>
                </div>
                <div>
                    <div className="inline-block align-bottom">
                        <button  onClick={() => router.push('contact')} className="bg-yellow-400 opacity-75 hover:opacity-100 
                        text-gray-900 hover:text-gray-900 rounded-full px-10 
                        py-2 font-semibold focus:outline-none"><i class="mdi mdi-cart -ml-2 mr-2"></i>
                         Contact Me </button>
                    </div>
                </div>
                <div>
                  

                <div class="py-6 flex flex-col justify-center sm:py-12">
  <div class="grid xl:grid-cols-6 lg:grid-cols-4 md:grid-cols-3 sm:grid-cols-6 grid-cols-3 gap-2 px-2">
   
    <div class="bg-gray-100 rounded-full border-[#ff3399]  bg-opacity-95 border-opacity-60 | p-4 border-solid  border-2 | flex justify-around cursor-pointer | hover:bg-[#ff99bb] hover:border-transparent | transition-colors duration-500">
      <img class="w-10 h-10 object-cover rounded-full lg:w-7 lg:h-7 " 
      src="https://image.flaticon.com/icons/png/512/2111/2111463.png" alt="" />
     
    </div>
    
    <div class="bg-gray-100 border-blue-400 rounded-full  bg-opacity-95 border-opacity-60 | p-4 border-solid  border-2 | flex justify-around cursor-pointer | hover:bg-blue-300  hover:border-transparent | transition-colors duration-500">
      <img class="w-10 h-10 object-cover rounded-full  lg:w-7 lg:h-7"
       src="https://image.flaticon.com/icons/png/512/145/145807.png" alt="" />
     
    </div>
    
    <div class="bg-gray-100 border-gray-800 rounded-full   bg-opacity-95 border-opacity-60 | p-4 border-solid  border-2 | flex justify-around cursor-pointer | hover:bg-gray-300  hover:border-transparent | transition-colors duration-500">
      <img class="w-10 h-10 object-cover  lg:w-7 lg:h-7"
       src="https://image.flaticon.com/icons/png/512/733/733609.png" alt="" />
      
    </div>
    
    <div class="bg-gray-100 border-red-600  rounded-full  bg-opacity-95 border-opacity-60 | p-4 border-solid  border-2 | flex justify-around cursor-pointer | hover:bg-red-400 hover:border-transparent | transition-colors duration-500">
      <img class="w-10 h-10 object-cover  lg:w-7 lg:h-7"
       src="https://image.flaticon.com/icons/png/512/732/732200.png" alt="" />
      
    </div>

    <div class="bg-gray-100 border-blue-400  rounded-full  bg-opacity-95 border-opacity-60 | p-4 border-solid  border-2 | flex justify-around cursor-pointer | hover:bg-blue-200 hover:border-transparent | transition-colors duration-500">
      <img class="w-10 h-10 object-cover  lg:w-7 lg:h-7"
       src="https://image.flaticon.com/icons/png/512/145/145812.png" alt="" />
      
    </div>

    <div class="bg-gray-100 border-gray-700  rounded-full  bg-opacity-95 border-opacity-60 | p-4 border-solid  border-2 | flex justify-around cursor-pointer | hover:bg-gray-300 hover:border-transparent | transition-colors duration-500">
      <img class="w-10 h-10 object-cover  lg:w-7 lg:h-7" 
      src="https://image.flaticon.com/icons/png/512/3670/3670068.png" alt="" />
      
    </div>
    
  </div>

</div>

                </div>
            </div>
        </div>
    </div>
</div>

      </main>
    </div>
  )
}
